"""empty message

Revision ID: 32e5e9a3576f
Revises: a27b5201e4e3
Create Date: 2026-08-10 20:47:17.651442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e5e9a3576f'
down_revision: Union[str, Sequence[str], None] = 'a27b5201e4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reported_status', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reported_status', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reported_status', 'updated_at')
    op.drop_column('reported_status', 'created_at')
    # ### end Alembic commands ###
